AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: This template deploys RDS Bootstrap Function
Parameters:
  FunctionName:
    Type: String
  CredentialsSecret:
    Type: String
  ApprovalDbClusterAddress:
    Type: String
  ApprovalDbClusterPort:
    Type: String
  InteractionDbClusterAddress:
    Type: String
  InteractionDbClusterPort:
    Type: String
  ApprovalDbClusterArn:
    Type: String
  ApprovalDbName:
    Type: String
  ApprovalDbSchemaName:
    Type: String
  FlagTable:
    Type: String
  UncloggerPromptTable:
    Type: String
  InteractionDbClusterArn:
    Type: String
  InteractionDbName:
    Type: String
  InteractionDbSchemaName:
    Type: String
  UserInteractionTable:
    Type: String
  ContentInteractionTable:
    Type: String
  CommentTable:
    Type: String
  Environment:
    Type: String
    Default: dev
  Application:
    Type: String
Resources:
  RdsBootstrapFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: ./
      Handler: "lambda_function.lambda_handler"
      Environment:
        Variables:
          CREDENTIALS_SECRET: !Ref CredentialsSecret
          APPROVAL_DB_ADDRESS: !Ref ApprovalDbClusterAddress
          APPROVAL_DB_PORT: !Ref ApprovalDbClusterPort
          INTERACTION_DB_ADDRESS: !Ref InteractionDbClusterAddress
          INTERACTION_DB_PORT: !Ref InteractionDbClusterPort
          APPROVAL_DB_CLUSTER_ARN: !Ref ApprovalDbClusterArn
          APPROVAL_DB_NAME: !Ref ApprovalDbName
          APPROVAL_DB_SCHEMA_NAME: !Ref ApprovalDbSchemaName
          FLAG_TABLE: !Ref FlagTable
          UNCLOGGER_PROMPT_TABLE: !Ref UncloggerPromptTable
          INTERACTION_DB_CLUSTER_ARN: !Ref InteractionDbClusterArn
          INTERACTION_DB_NAME: !Ref InteractionDbName
          INTERACTION_DB_SCHEMA_NAME: !Ref InteractionDbSchemaName
          USER_INTERACTION_TABLE: !Ref UserInteractionTable
          CONTENT_INTERACTION_TABLE: !Ref ContentInteractionTable
          COMMENT_TABLE: !Ref CommentTable
          APPLICATION_TAG: !Ref Application
          ENVIRONMENT_TAG: !Ref Environment
      MemorySize: 128
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "logs:*"
                - "rds-data:ExecuteSql"
                - "rds-data:ExecuteStatement"
                - "secretsmanager:GetSecretValue"
                - "events:PutRule"
                - "events:DeleteRule"
                - "events:PutTargets"
                - "events:RemoveTargets"
              Resource: "*"
      Runtime: python3.8
      Timeout: 900
      Tags:
        Environment: !Ref Environment
        Application: !Ref Application
