AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: This template deploys RDS Bootstrap Function
Parameters:
  FunctionName:
    Type: String
  CredentialsSecret:
    Type: String
  ApprDbAddress:
    Type: String
  ApprDbPort:
    Type: String
  IntactDbAddress:
    Type: String
  IntactDbPort:
    Type: String
  ApprDbArn:
    Type: String
  ApprDbName:
    Type: String
  ApprDbSchema:
    Type: String
  FlagTbl:
    Type: String
  UncloggerPromptTbl:
    Type: String
  IntactDbArn:
    Type: String
  IntactDbName:
    Type: String
  IntactDbSchema:
    Type: String
  UserInteractionTbl:
    Type: String
  ContentInteractionTbl:
    Type: String
  CommentTbl:
    Type: String
  Environment:
    Type: String
    Default: dev
  Application:
    Type: String
Resources:
  RdsBootstrapFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: ./
      Handler: "lambda_function.lambda_handler"
      Environment:
        Variables:
          CREDENTIALS_SECRET: !Ref CredentialsSecret
          APPROVAL_DB_ADDRESS: !Ref ApprDbAddress
          APPROVAL_DB_PORT: !Ref ApprDbPort
          INTERACTION_DB_ADDRESS: !Ref IntactDbAddress
          INTERACTION_DB_PORT: !Ref IntactDbPort
          APPROVAL_DB_CLUSTER_ARN: !Ref ApprDbArn
          APPROVAL_DB_NAME: !Ref ApprDbName
          APPROVAL_DB_SCHEMA_NAME: !Ref ApprDbSchema
          FLAG_TABLE: !Ref FlagTbl
          UNCLOGGER_PROMPT_TABLE: !Ref UncloggerPromptTbl
          INTERACTION_DB_CLUSTER_ARN: !Ref IntactDbArn
          INTERACTION_DB_NAME: !Ref IntactDbName
          INTERACTION_DB_SCHEMA_NAME: !Ref IntactDbSchema
          USER_INTERACTION_TABLE: !Ref UserInteractionTbl
          CONTENT_INTERACTION_TABLE: !Ref ContentInteractionTbl
          COMMENT_TABLE: !Ref CommentTbl
          APPLICATION_TAG: !Ref Application
          ENVIRONMENT_TAG: !Ref Environment
      MemorySize: 128
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "logs:*"
                - "rds-data:ExecuteSql"
                - "rds-data:ExecuteStatement"
                - "secretsmanager:GetSecretValue"
                - "events:PutRule"
                - "events:DeleteRule"
                - "events:PutTargets"
                - "events:RemoveTargets"
              Resource: "*"
      Runtime: python3.8
      Timeout: 900
      Tags:
        Environment: !Ref Environment
        Application: !Ref Application
